baseURL = "https://cont.fitedu.ru/"
languageCode = "ru"
defaultContentLanguage = "en"
title = "Наши контакты"
enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Fitness Holding Forum 2025"
  headline = "Связаться"
  image = "/img/author.png"

  links = [
     { booking = { href = "https://fhforum.ru/", text = "Сайт" } },
     { booking = { href = "https://vk.com/russianinstituteoffitness", text = "VK" } },
     { telegram = "https://t.me/rifedu_official" },
     { whatsapp = "https://wa.me/+79266074000" },
     { email = "mailto:info@fitinstitute.ru" }
  ]

[module]
  [module.hugoVersion]
    extended = false
    min = "0.86.1"
